#!/usr/bin/env python
import click
from click import echo
import build_xml
import build_html
import build_index

@click.group()
def build():
	pass

build_xml.click(build)
build_html.click(build)
build_index.click(build)

if __name__ == '__main__':
    build()
